# Oxygen

spacing         = 3
hide_ascii      = true
key_color       = "#89b4fa"
separator       = ""

[box]
title           = "   System information "
border          = "rounded"
visible         = true

[palette]
glyph           = "●"
spacing         = 2
visible         = true

[bar]
glyph           = "●"
hide_delimiters = true
visible         = true

[box.inner_margin]
x               = 1
y               = 1

[custom_ascii]
color           = "#9ccfd8"
path            = "/home/samsepi0l/miniarch.txt"
visible         = true

[keys]
host = "Host"
